---
- name: Iniciar instancia EC2
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aws_region: "us-east-1"
    ec2_instance_id: "i-056080d28ad720d8e"

  tasks:

    - name: Iniciar instancia EC2
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        instance_ids:
          - "{{ ec2_instance_id }}"
        state: running
        wait: true
      register: ec2_result

    - name: Exibir resultado
      ansible.builtin.debug:
        msg:
          instance_id: "{{ ec2_instance_id }}"
          region: "{{ aws_region }}"
          state: "{{ ec2_result.instances[0].state.name | default('unknown') }}"